api_key =                   # your coinbase api-key
api_secret =                # your coinbase api secret
period = 320               	# seconds to ping for prices
pair = "BTC-EUR"
lengthOfMA = 120            # vector prices log
market_fees = 3.1          	# coinbase per-transaction fee in dollars
min_profit_margin = 2     	# minimum % increase before we sell out 
strategy = "combined"       # MACD, RSI, Combined
webserver = False          	#activate web server for report on http://localhost/index.html
interpolation = "yes"		#lines become smooth
graphical = True			# trace a chart of operation in 
buy_sell_amount = 100		# Eur per Buy
buy_limit = 1				# maximum number of pachet of buy_sell_amount to buy
ignore_signals_after = 8	# ignore pending signals after a number of period s. 
RSI_top_lim = 70			# RSI max thresold
RSI_down_lim = 30			# RSI min thresold
